### ISSUE TITLE
Issues defining the middle point

### ISSUE THREAD

**Issue by aron-adc** [DCBIA-OrthoLab/Q3DCExtension#19] opened 2019-12-17 17:23 UTC
@jcfr @bpaniagua @luciacev 
Hi,
we are using the function “define middle point between two landmarks” and having two issues:
1.	ISSUE
The middle point is given the numbering of the next fiducial, and the user does not know which fiducials were used to define that middle point. would it be possible to modify the code to automatically name the middle point? for example, the middle defined from fiducials “1” and “2” could be fiducial “1_2”? 

POSSIBLE SOLUTION: it will be very helpful for users to automatically know the landmarks(fiducials) that were used to define the middle point.

2.	ISSUE
 The middle point between 2 surfaces fiducials is usually in the “air” and not in the surface of a mesh. after you save the fiducial list, when a user opens the fiducial list again, the middle points are automatically displaced to stick to the surface mesh. 

POSSIBLE SOLUTION:
would it be possible to keep the middle points in the same spatial position that they were defined, instead of sticking to the surface when we reopen the fiducials list? only the fiducials placed on the surface meshes should stick to the surface, but not the computed middle points. one possible solution could be to have a column in   the fiducial list where users could select with fiducials should stick or not  to the surface before saving the fiducial list. 

Thank you in advance,

**Comment by JEHoctor** [comment] 2020-03-03 19:19
@aron-adc 

My commit above makes the two "On Surface" check boxes appear unchecked initially. My thought is that projection is not what most users want anyway.

We can add "conditional sticking" in the future if it's important to you. One thing that complicates the "conditional sticking" idea is the question of what should happen to a midpoint after its corresponding endpoints have been moved. It likely makes sense for the midpoint to move to the new location between these points.

Anyway, I'm hoping changing the defaults is good enough!

**Comment by luciacev** [comment] 2020-03-04 00:54
Thanks so much James!
Projection to the surface is used by most users for most fiducials: as most
fiducials are projected to the surface..;

This issue reported by ARON happens  when a fiducial list contains both
fiducials projected on the surface and  fiducials that are determined by
the mid-distance between two surface landmarks.. that midistance cannot be
on the surface...

Please let me know if this helps any or you need further clarification.

Best
Lucia

**Comment by JEHoctor** [comment] 2020-03-05 17:34
Ah, well I had to try the easy way first! ¯\\\_(ツ)\_/¯

I'll take a look at the code for new landmarks.

**Comment by JEHoctor** [comment] 2020-03-06 21:51
@luciacev @bpaniagua 

I have just had success with the sample data you provided us with @luciacev, after this commit: https://github.com/JEHoctor/Q3DCExtension/commit/41ad7fcdb78563282d12f0b585ca325428e778ee.

You provided us with two matched .vtk/.fcvs pairs of files. I have confirmed that with the first pair, when projection is enabled with the "On Surface" checkbox, and the fiducial list is selected in the "Connected Landmarks" box, the midpoints are no longer projected; they are treated separately.

I still need to test:

1. The second example pair of files should work also.
2. Everything should still work correctly when the box is not checked.
3. Projection of surface points should work, for example when the first fiducial list you provided is used with the second vtk mesh you provided.
4. Midpoints should more whenever the corresponding surface points move.

This code cannot handle the case of a midpoint that is constructed from another midpoint. I can attempt to address that if you like.

A recent change in Slicer nightly will likely require you to select "RAS" as the coordinate system for old vtk files. This affects at least one of sample vtk files you provided me with.

**Comment by JEHoctor** [comment] 2020-03-06 23:04
1. I believe my points 1-3 above are working.
2. Point 4 works on a "fresh" fiducial list but not when moving a fiducial list from model to model. The code to fix here is likely in the method called `changementOfConnectedModel`.
3. The "midpoints from midpoints" problem seems solvable to me.
4. My new code fails with empty fiducial lists (for example, newly create lists).

**Comment by JEHoctor** [comment] 2020-03-06 23:27
A further standing issue with my solution is that in some cases a fiducial that is "unselected" in the fcsv, indicating that it is a midpoint, will not be a midpoint of any pair of fiducials in the list. In this case, it should be selected, to indicate that it will not be treated as a midpoint.

**Comment by JEHoctor** [comment] 2020-03-26 17:48
@aron-adc @luciacev 
I have implemented the naming behavior you asked for ("1" + "2" --> "1_2”) in my patch https://github.com/JEHoctor/Q3DCExtension/commit/93e1ecabbc743d14721868881a2a8bada5732168.

Because a midpoint is sometimes defined by points with long names, the name of the resulting midpoint is sometimes even longer/more cumbersome. Another naming scheme that might be good is "blah-1" + "blah-2" --> "blah-1_2". Let me know if you want this, or some other scheme.

**Comment by JEHoctor** [comment] 2020-03-26 18:22
@aron-adc @luciacev 
I made a pull request for the changes I've made. Tomorrow the changes will be available in Slicer nightly. Tomorrow, go to https://download.slicer.org/ and download the "Preview Release" version of Slicer for your operating system. Then use the Extensions Manager to get Q3DC. Let me know how these changes work for you. Remember to test both Aron's issue 1 and issue 2.

**Comment by luciacev** [comment] 2020-03-26 18:54
@aron-adc @JEHoctor @aruellas @cdasilve @DCBIA-OrthoLab/owners @bpaniagua @jcfr 
Thanks so much James! We will test your work for issues 1 and 2 reported by Aron.

**Comment by JEHoctor** [comment] 2020-04-20 16:17
I recommend closing this issue at this point.

**Closed** 2020-06-09 22:59 UTC
